[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set environment variables used during the build
[build.environment]
  NODE_VERSION = "18"

# Development environment settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Headers to set for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 